#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo -e '\e[32m _________________________________________________________________\n\e[m'
echo -e '\e[32m 🏗️👷 Styling, testing and building your project before committing\n\e[m'
echo -e '\e[32m _________________________________________________________________\e[m'

# Check Prettier standards
npm run check-format ||
(
    echo -e '\e[31m 🤢🤮🤢🤮 Its F**KING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run npm run format, add changes and try commit again.\e[m';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo -e '\e[31m 😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.\e[m'
        false;
)

# Check tsconfig standards
#npm run check-types ||
#(
#    echo -e '\e[31m 🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
#            Are you seriously trying to write that? Make the changes required above.\e[m'
#    false;
#)

# If everything passes... Now we can commit
echo -e '\e[32m 🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔\e[m'

npm run build ||
(
   echo -e '\e[31m ❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why.\e[m'
    false;
)

# If everything passes... Now we can commit
echo -e '\e[32m✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅\e[m'
